services:
  - type: web
    name: amr-backend
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      cd backend && pip install -r requirements.txt
      cd backend && python manage.py collectstatic --noinput
    startCommand: cd backend && python manage.py migrate && python create_superuser.py && gunicorn amr_project.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:your_actual_password@ep-little-pine-ada2gu0j-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com,localhost,127.0.0.1
      - key: CORS_ALLOWED_ORIGINS
        value: https://amrfrontend.netlify.app,http://localhost:5173
      - key: DJANGO_SETTINGS_MODULE
        value: amr_project.settings_production
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@example.com
      - key: DJANGO_SUPERUSER_PASSWORD
        generateValue: true
