# Generated by Django 5.2.6 on 2025-10-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100)),
                ('specimen_type', models.CharField(max_length=100)),
                ('organism', models.CharField(max_length=100)),
                ('antibiotic', models.CharField(max_length=100)),
                ('susceptibility', models.CharField(max_length=50)),
                ('test_date', models.DateField()),
                ('facility', models.CharField(max_length=200)),
                ('patient_age', models.IntegerField(blank=True, null=True)),
                ('patient_sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'amr_lab_results',
            },
        ),
    ]
